[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
serde = { version = "1.0", features = ["derive"] }

[dependencies]
json = "0.12.4"
serde = "1.0.152"
serde_json = "1.0.93"
